"""
Metadata per testcase: beschrijving, eis, prioriteit, teststappen en conclusie-templates.
Wordt gebruikt door manual_entry.py, generate_report.py en save_results() in helpers.py.
"""

TC_META = {
    "TC-001": {
        "description": "Inloggen met geldige gegevens",
        "eis": "FE1",
        "prioriteit": "Hoog",
        "stappen": [
            "Navigeer naar de startpagina (`/talent`)",
            "Klik op het login-icoon (`section#login i.material-icons`) in de navigatiebalk",
            "Keycloak-loginpagina laadt op extern domein",
            "Vul geldige gebruikersnaam en wachtwoord in",
            'Klik op "Sign In"',
        ],
        "conclusie_geslaagd": "Inloggen werkt correct. De applicatie stuurt de gebruiker terug naar de startpagina en toont het logout-icoon.",
        "conclusie_gefaald": "Inloggen werkt niet correct.",
    },
    "TC-002": {
        "description": "Inloggen met onjuist wachtwoord",
        "eis": "FE1",
        "prioriteit": "Hoog",
        "stappen": [
            "Navigeer naar de startpagina (`/talent`) — frisse sessie (niet ingelogd)",
            "Klik op het login-icoon in de navigatiebalk",
            "Keycloak-loginpagina laadt",
            "Vul geldige gebruikersnaam in, maar een onjuist wachtwoord",
            'Klik op "Sign In"',
        ],
        "conclusie_geslaagd": "Het systeem toont de juiste foutmelding en stuurt de gebruiker niet door. Werkt correct.",
        "conclusie_gefaald": "Het systeem geeft geen of onjuiste foutmelding.",
    },
    "TC-003": {
        "description": "Inloggen met onbekend e-mailadres",
        "eis": "FE1",
        "prioriteit": "Gemiddeld",
        "stappen": [
            "Navigeer naar de startpagina (`/talent`) — handmatig, Firefox",
            "Klik op het login-icoon in de navigatiebalk",
            "Keycloak-loginpagina laadt",
            "Vul een onbekend e-mailadres in (`ditbestaaniet@test.nl`) en willekeurig wachtwoord",
            'Klik op "Sign In"',
        ],
        "conclusie_geslaagd": "Het systeem maakt geen onderscheid tussen onbekend account en fout wachtwoord. Werkt correct.",
        "conclusie_gefaald": "Het systeem geeft een onverwachte of ontbrekende foutmelding.",
    },
    "TC-004": {
        "description": "Uitloggen",
        "eis": "FE2",
        "prioriteit": "Hoog",
        "stappen": [
            "Log in met geldige gegevens (zie TC-001)",
            "Klik op het logout-icoon in de navigatiebalk",
        ],
        "conclusie_geslaagd": "Uitloggen werkt correct. De applicatie toont het login-icoon en verbergt het logout-icoon.",
        "conclusie_gefaald": "Uitloggen werkt niet correct.",
    },
    "TC-005": {
        "description": "Sessie beëindigd na uitloggen",
        "eis": "FE2",
        "prioriteit": "Hoog",
        "stappen": [
            "Log in met geldige gegevens (zie TC-001)",
            "Navigeer naar een talentprofiel (`/talent/talentprofile/1`)",
            "Klik op het logout-icoon in de navigatiebalk",
            "Klik op de terugknop van de browser",
        ],
        "conclusie_geslaagd": "Na uitloggen stuurt de terugknop de gebruiker niet terug naar het talentprofiel maar naar de startpagina. De applicatie beëindigt de sessie correct en voorkomt actief toegang tot beschermde content.",
        "conclusie_gefaald": "Na uitloggen toont de terugknop nog steeds beschermde content. De sessie wordt niet correct beëindigd.",
    },
    "TC-006": {
        "description": "Talentprofiel afgeschermd voor bezoekers",
        "eis": "FE3",
        "prioriteit": "Hoog",
        "stappen": [
            "Zorg dat je niet ingelogd bent",
            "Navigeer direct naar een talentprofiel via de URL (bijv. `/talent/talentprofile/1`)",
        ],
        "conclusie_geslaagd": "Naam en contactgegevens zijn niet zichtbaar voor niet-ingelogde gebruikers. Een inlog call-to-action is aanwezig.",
        "conclusie_gefaald": "Beschermde persoonsgegevens zijn zichtbaar zonder login.",
    },
    "TC-007": {
        "description": "Admin panel toegankelijkheid per rol",
        "eis": "FE3",
        "prioriteit": "Hoog",
        "stappen": [
            "Navigeer als bezoeker (niet ingelogd) naar `/admin`",
            "Navigeer als ingelogde gebruiker (niet-admin) naar `/admin`",
            "Navigeer als beheerder naar `/admin`",
        ],
        "conclusie_geslaagd": "Alleen de beheerder heeft toegang tot het admin panel. Bezoekers en niet-admin gebruikers worden omgeleid.",
        "conclusie_gefaald": "Het admin panel is toegankelijk voor onbevoegde gebruikers.",
    },
    "TC-008": {
        "description": "Filteren op provincie",
        "eis": "FE4",
        "prioriteit": "Hoog",
        "stappen": [
            "Navigeer naar de talentenpagina (`/talent`)",
            "Noteer het aantal getoonde talenten",
            "Selecteer een provincie via het provinciefilter (bijv. Noord-Brabant)",
            "Bekijk de gefilterde resultaten",
        ],
        "conclusie_geslaagd": "Alleen talenten uit de geselecteerde provincie worden getoond. Het filter werkt correct.",
        "conclusie_gefaald": "Het filter toont onjuiste of geen resultaten.",
    },
    "TC-009": {
        "description": "Filteren op beschikbaarheid (grenswaarden)",
        "eis": "FE4",
        "prioriteit": "Hoog",
        "stappen": [
            "Navigeer naar de talentenpagina (`/talent`)",
            "Noteer welke talenten beschikbaar zijn en hoeveel uur zij beschikbaar zijn",
            "Stel een ondergrens en bovengrens in voor beschikbaarheid (bijv. 20–32 uur)",
            "Controleer de gefilterde resultaten",
        ],
        "conclusie_geslaagd": "Alleen talenten binnen het opgegeven beschikbaarheidsbereik worden getoond. Grenswaarden worden correct verwerkt.",
        "conclusie_gefaald": "Het beschikbaarheidsfilter toont onjuiste resultaten of verwerkt grenswaarden incorrect.",
    },
    "TC-010": {
        "description": "Talentprofiel volledig zichtbaar voor ingelogde gebruiker",
        "eis": "FE5",
        "prioriteit": "Hoog",
        "stappen": [
            "Log in met geldige gegevens (zie TC-001)",
            "Navigeer naar een talentprofiel (bijv. `/talent/talentprofile/1`)",
        ],
        "conclusie_geslaagd": "Alle verwachte profielattributen zijn zichtbaar voor de ingelogde gebruiker.",
        "conclusie_gefaald": "Een of meer verwachte profielattributen ontbreken.",
    },
    "TC-011": {
        "description": "Talentprofiel gedeeltelijk zichtbaar voor bezoeker",
        "eis": "FE5",
        "prioriteit": "Hoog",
        "stappen": [
            "Zorg dat je niet ingelogd bent",
            "Navigeer direct naar een talentprofiel via de URL (bijv. `/talent/talentprofile/1`)",
        ],
        "conclusie_geslaagd": "Persoonsgegevens zijn verborgen; publieke attributen en een inlog call-to-action zijn zichtbaar.",
        "conclusie_gefaald": "De zichtbaarheid van profielinformatie voor bezoekers is onjuist.",
    },
    "TC-012": {
        "description": "IDOR — talentprofiel via URL-manipulatie",
        "eis": "NFE1/NFE3",
        "prioriteit": "Hoog",
        "stappen": [
            "Zorg dat je niet ingelogd bent",
            "Navigeer naar `/talent/talentprofile/1`",
            "Noteer welke gegevens zichtbaar zijn",
            "Verander het ID in de URL naar `/talent/talentprofile/2`, `/3`, etc.",
            "Controleer per profiel welke gegevens zichtbaar zijn",
        ],
        "conclusie_geslaagd": "Voor geen enkel profiel zijn naam of contactgegevens zichtbaar zonder login. Geen IDOR-kwetsbaarheid aangetoond.",
        "conclusie_gefaald": "Persoonsgegevens zijn toegankelijk via URL-manipulatie zonder login.",
    },
    "TC-013": {
        "description": "Talent aanmaken",
        "eis": "FE11",
        "prioriteit": "Hoog",
        "stappen": [
            "Log in als beheerder (zie TC-001)",
            "Navigeer naar `/admin/talenten`",
            'Klik op "Talent toevoegen"',
            "Vul de verplichte velden in met testdata (voornaam: Test, achternaam: Talent, etc.)",
            "Sla het talent op",
        ],
        "conclusie_geslaagd": "Het nieuwe talent verschijnt in de talentenlijst op `/admin/talenten`.",
        "conclusie_gefaald": "Het talent wordt niet aangemaakt of verschijnt niet in de lijst.",
    },
    "TC-014": {
        "description": "Talent bewerken",
        "eis": "FE11",
        "prioriteit": "Hoog",
        "stappen": [
            "Log in als beheerder (zie TC-001)",
            "Navigeer naar `/admin/talenten`",
            'Klik op "Edit" bij het talent Test Talent',
            "Wijzig de woonplaats van `Teststad` naar `Gewijzigdstad`",
            "Sla de wijziging op",
        ],
        "conclusie_geslaagd": "De woonplaats is bijgewerkt naar `Gewijzigdstad` in de talentenlijst.",
        "conclusie_gefaald": "De wijziging wordt niet opgeslagen of is niet zichtbaar.",
    },
    "TC-015": {
        "description": "Talent verwijderen",
        "eis": "FE11",
        "prioriteit": "Hoog",
        "stappen": [
            "Log in als beheerder (zie TC-001)",
            "Navigeer naar `/admin/talenten`",
            'Klik op "Delete" bij het talent Test Talent',
            "Bevestig de verwijdering indien gevraagd",
        ],
        "conclusie_geslaagd": "Het talent is niet meer zichtbaar in de talentenlijst.",
        "conclusie_gefaald": "Het talent is nog steeds aanwezig na verwijdering.",
    },
    "TC-016": {
        "description": "Werkervaring toevoegen",
        "eis": "FE11",
        "prioriteit": "Gemiddeld",
        "stappen": [
            "Log in als beheerder en navigeer naar `/admin/talenten`",
            'Klik op "Edit" bij een bestaand talent',
            'Open het paneel "Werkervaring"',
            "Voeg een nieuwe werkervaringsregel toe (werkgever: Test BV, functie: Tester, periode: 2023–2024)",
            "Sla het talent op",
        ],
        "conclusie_geslaagd": "De werkervaring is zichtbaar in het profiel van het talent.",
        "conclusie_gefaald": "De werkervaring wordt niet opgeslagen of is niet zichtbaar.",
    },
    "TC-017": {
        "description": "Werkervaring bewerken",
        "eis": "FE11",
        "prioriteit": "Gemiddeld",
        "stappen": [
            "Log in als beheerder en navigeer naar het bewerkscherm van een talent met werkervaring",
            'Open het paneel "Werkervaring"',
            "Bewerk de functietitel (bijv. van `Tester` naar `Senior Tester`)",
            "Sla het talent op",
        ],
        "conclusie_geslaagd": "De gewijzigde functietitel is zichtbaar in het profiel van het talent.",
        "conclusie_gefaald": "De wijziging wordt niet opgeslagen.",
    },
    "TC-018": {
        "description": "Werkervaring verwijderen",
        "eis": "FE11",
        "prioriteit": "Gemiddeld",
        "stappen": [
            "Log in als beheerder en navigeer naar het bewerkscherm van een talent met werkervaring",
            'Open het paneel "Werkervaring"',
            "Verwijder een werkervaringsregel",
            "Sla het talent op",
        ],
        "conclusie_geslaagd": "De verwijderde werkervaring is niet meer zichtbaar in het profiel.",
        "conclusie_gefaald": "De werkervaring is nog steeds zichtbaar na verwijdering.",
    },
    "TC-019": {
        "description": "Opleiding toevoegen",
        "eis": "FE11",
        "prioriteit": "Gemiddeld",
        "stappen": [
            "Log in als beheerder en navigeer naar het bewerkscherm van een talent",
            'Open het paneel "Opleidingen"',
            "Voeg een opleiding toe (opleiding: Software Developer, instelling: Test ROC, jaar: 2022)",
            "Sla het talent op",
        ],
        "conclusie_geslaagd": "De opleiding is zichtbaar in het profiel van het talent.",
        "conclusie_gefaald": "De opleiding wordt niet opgeslagen.",
    },
    "TC-020": {
        "description": "Opleiding bewerken",
        "eis": "FE11",
        "prioriteit": "Gemiddeld",
        "stappen": [
            "Log in als beheerder en navigeer naar het bewerkscherm van een talent met een opleiding",
            'Open het paneel "Opleidingen"',
            "Wijzig het afstudeerjaar (bijv. van `2022` naar `2023`)",
            "Sla het talent op",
        ],
        "conclusie_geslaagd": "Het gewijzigde jaar is zichtbaar in het profiel van het talent.",
        "conclusie_gefaald": "De wijziging wordt niet opgeslagen.",
    },
    "TC-021": {
        "description": "Opleiding verwijderen",
        "eis": "FE11",
        "prioriteit": "Gemiddeld",
        "stappen": [
            "Log in als beheerder en navigeer naar het bewerkscherm van een talent met een opleiding",
            'Open het paneel "Opleidingen"',
            "Verwijder een opleiding",
            "Sla het talent op",
        ],
        "conclusie_geslaagd": "De verwijderde opleiding is niet meer zichtbaar in het profiel.",
        "conclusie_gefaald": "De opleiding is nog steeds zichtbaar na verwijdering.",
    },
    "TC-022": {
        "description": "Hobby/interesse toevoegen",
        "eis": "FE11",
        "prioriteit": "Laag",
        "stappen": [
            "Log in als beheerder en navigeer naar het bewerkscherm van een talent",
            "Open het paneel \"Hobby's (& Interesses)\"",
            "Voeg een hobby toe (bijv. `Schaken`)",
            "Sla het talent op",
        ],
        "conclusie_geslaagd": "De hobby is zichtbaar in het profiel van het talent.",
        "conclusie_gefaald": "De hobby wordt niet opgeslagen.",
    },
    "TC-023": {
        "description": "Hobby/interesse verwijderen",
        "eis": "FE11",
        "prioriteit": "Laag",
        "stappen": [
            "Log in als beheerder en navigeer naar het bewerkscherm van een talent met een hobby",
            "Open het paneel \"Hobby's (& Interesses)\"",
            "Verwijder een hobby",
            "Sla het talent op",
        ],
        "conclusie_geslaagd": "De verwijderde hobby is niet meer zichtbaar in het profiel.",
        "conclusie_gefaald": "De hobby is nog steeds zichtbaar na verwijdering.",
    },
    "TC-024": {
        "description": "Hobby/interesse sorteren",
        "eis": "FE11",
        "prioriteit": "Laag",
        "stappen": [
            "Log in als beheerder en navigeer naar het bewerkscherm van een talent met meerdere hobby's",
            "Open het paneel \"Hobby's (& Interesses)\"",
            "Verander de volgorde van twee hobby's (bijv. via slepen of prioriteitsknop)",
            "Sla het talent op",
        ],
        "conclusie_geslaagd": "De nieuwe volgorde van hobby's is zichtbaar in het profiel van het talent.",
        "conclusie_gefaald": "De volgorde wordt niet opgeslagen.",
    },
}
